export default{
    PRIMARY_COLOR: "#C2A77A", //Green
    PRIMARY_COLOR_DARK: "#357443",
    PRIMARY_COLOR_LIGHT: "#61DF7D", 

    SECONDARY_COLOR:"#fff", //White
    SECONDARY_COLOR_DARK: "#C7C7C7",

    TERTIARY_COLOR:"#000", //Black
    TERTIARY_COLOR_LIGHT: "#4E4E4E", 

    NAV_BAR_ICON:"#e5d3b3"
    
};